### ISSUE TITLE
Resilience to broken downtime if we want to.

### ISSUE THREAD

**Issue by Jan-M** [zalando-zmon/zmon-worker#84]
Ideally this should be handled gracefully triggering the alert, right now this does not get executed or reporated add all

```
ERROR [worker-35] zmon_worker_monitor.zmon_worker.tasks.main/notify: Notification for check Webapp HTTP Status reached soft time limit
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zmon_worker-cd156-py2.7.egg/zmon_worker_monitor/zmon_worker/tasks/main.py", line 1445, in notify
    downtimes = self._evaluate_downtimes(alert_id, entity_id)
  File "/usr/local/lib/python2.7/dist-packages/zmon_worker-cd156-py2.7.egg/zmon_worker_monitor/zmon_worker/tasks/main.py", line 1635, in _evaluate_downtimes
    if now > d['start_time'] and now < d['end_time']:
KeyError: 'start_time'
```

**Comment by mohabusama** [comment]
So if the downtime is broken, we ignore it? @Jan-M

**Comment by Jan-M** [comment]
yes
